### ISSUE TITLE
9.2 clash resolution in API

### ISSUE THREAD

**Issue by meiying13** [Tink-A-Ton/assessment-scheduler#11]
**Description:**

Controllers and views for handling clash detection need to be implemented to ensure that conflicts are identified by the system in a consistent and automated manner.

**Proposed Solution:**
- Create controllers for clash detection.
- Create views for clash detection.

**Benefits:**
- Provides a seamless process for detecting clashes.
- Improves system reliability by automating conflict detection.

**Comment by carrot2803** [comment]
Addressed :)
