### ISSUE TITLE
Refactor Application to Support Exam Scheduling Only

### ISSUE THREAD

**Issue by meiying13** [Tink-A-Ton/assessment-scheduler#18]
**Description:**

Based on feedback, the application requires refactoring to focus exclusively on exam scheduling by removing dependencies and models related to other assessment types.

**Proposed Solution:**
- Remove the `AssessmentType` model from the codebase.
- Refactor the `CourseAssessment` model to align with exam-specific requirements.
- Eliminate any `AssessmentType` dependencies in controllers, views, and UI components.

**Benefits:**
- Streamlines the application for exam scheduling.
- Reduces complexity by narrowing scope and removing unnecessary models and dependencies.

**Comment by meiying13** [comment]
codebase was successfully refactored to only support the scheduling of exams

**Comment by carrot2803** [comment]
Merge mildly improper WIP fixes shouldnt be reflected in development
