### ISSUE TITLE
8.8 refactor core controllers

### ISSUE THREAD

**Issue by carrot2803** [Tink-A-Ton/assessment-scheduler#27]
**Description:**

The core controllers, including the _**assessment**_ and _**course**_ controllers, need to be refactored to align with the newly updated model schema. The goal is to ensure these controllers are well-defined and used efficiently within the application.

**Proposed Solution:**
- Refactor the _**assessment**_ controller to align with the new model schema.
- Refactor the _**course**_ controller to improve structure and performance.
- Remove any unused or redundant controller methods.
- Ensure that both controllers follow best practices for performance and maintainability.

**Benefits:**
- Ensures the controllers are up-to-date with the new model schema.
- Improves the overall performance and efficiency of the application.
- Enhances maintainability by removing unnecessary code and ensuring clear controller responsibilities.

**Comment by meiying13** [comment]
refactor was completed and the pull request was approved
